services:
  artisian_db:
    image: postgres:13
    env_file:
      - .env.db.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
