"""Fixed Pydantic schema typo for MessageBase.

Revision ID: 864297718de4
Revises: 6f0c8bd8f320
Create Date: 2024-11-07 15:05:41.518985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864297718de4'
down_revision: Union[str, None] = '6f0c8bd8f320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
